# -*- coding: utf-8 -*-
"""milestone project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FIpebVuswAhfhhohQvbaKvy4PwkQbluw
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

attendance = pd.read_csv(
    "/content/internship_attendance_980_students.csv"
)

attendance.head()

print("Dataset Shape:", attendance.shape)

plt.figure(figsize=(8,6))

certified = summary[
    summary["Certificate"] == 1
]

uncertified = summary[
    summary["Certificate"] == 0
]

plt.scatter(
    certified["Days_Attended"],
    certified["Attendance_Percentage"],
    label="Certified"
)

plt.scatter(
    uncertified["Days_Attended"],
    uncertified["Attendance_Percentage"],
    label="Uncertified"
)

plt.xlabel("Days Attended")
plt.ylabel("Attendance Percentage")
plt.title("Certified vs Uncertified Students")
plt.legend()

plt.show()

summary = attendance.groupby(
    "Student_Name"
)["Present"].sum().reset_index()

summary.rename(
    columns={"Present":"Days_Attended"},
    inplace=True
)

TOTAL_DAYS = 40

summary["Attendance_Percentage"] = (
    summary["Days_Attended"] / TOTAL_DAYS
) * 100

summary["Certificate"] = np.where(
    summary["Attendance_Percentage"] >= 80,
    1,
    0
)

X = summary[
    ["Days_Attended", "Attendance_Percentage"]
]

y = summary["Certificate"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(
    y_test,
    y_pred
)

print("Accuracy:", accuracy)

total_students = len(summary)

eligible_students = int(
    summary["Certificate"].sum()
)

not_eligible_students = (
    total_students -
    eligible_students
)

print("Total Students:", total_students)
print("Students Eligible for Certificate:", eligible_students)
print("Students Not Eligible for Certificate:", not_eligible_students)

summary.to_csv(
    "attendance_summary.csv",
    index=False
)